language: python
python:
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: haydenflinner
  password:
    secure: bGTrJoNkaaoOzO7BgD10M4lNyDEl3KxibJ+KrtpPclBY9gfUzgYA4tHAcLgHisSrfDtgy1uSa2Afoq37nnkybhvZ+Z80Qo5GfDRT1Vjeew+QUT9do1KyqxabnUecEV9UpcYo6RoqbtoPMUly1Vg0E8R6imWmrr7X9p/X4ENxf9S7jAEisStLLGEuxaL6DovdZ95TrEuUl+676UlTga/ALJwAQ6prsIydHWz91lP878jwB6XAPdz9bpLVXtGF8rdQXafAoxwsDg2HghA5yNICySQKj/fHIOPMQzKmhm15mUtu54g1j4SR5B5Cf3jwvNtJcM3/U/G/EncN5tU1HdiYKd7T8qrfS63xjPN4Qm33UPJwZULWIKH42ZiLyzB68HOs9lyYUlKWRu8fmwczqpQ21E0XG1ZOUCucUSP4KknIqjRYZ61g2xbcX89wbpasSOYYmVucdxtzKRuJ9KEM1XHiqolglHFr/YVRRPRULwUeaWFIjJt8j+Y2rZU6tBOMaL4KSg4LBIQWMatxmLM6F42j4Q6pz2W6PsqUY/SDvFriKroVX6RSLHUy+GTmMi1+wrPAJJClaucd0Hx3elivE6E18UIXWW/pNXnH3hKMDUSwMW0BNhkaDIJyGF6v3JygkzJJGamHImXhlhMXt5Gu3+FKQlfu5yIinq4TIh6J8mWdtJQ=
  on:
    tags: true
    repo: haydenflinner/cachepath
    python: 3.6
